package dz.mahasebi.pro.server;

import android.app.*;import android.content.*;import android.os.*;import android.database.sqlite.*;import android.database.Cursor;import android.net.Uri;
import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import javax.crypto.Mac;import javax.crypto.spec.SecretKeySpec;import java.util.*;

public class ServerService extends Service {
 public static final String ACTION_TOGGLE="dz.mahasebi.pro.TOGGLE_SERVER"; static final int PORT=8787; volatile boolean running=false; ServerThread thread; DB db;
 @Override public void onCreate(){super.onCreate();db=new DB(this);createChannel();}
 @Override public int onStartCommand(Intent i,int flags,int id){startForeground(77,notification()); if(!running){running=true;thread=new ServerThread();thread.start();} return START_STICKY;}
 @Override public void onDestroy(){running=false;try{if(thread!=null)thread.close();}catch(Exception e){} super.onDestroy();}
 @Override public IBinder onBind(Intent i){return null;}
 void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("mah_server","محاسبي PRO Server",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(c);}}
 Notification notification(){return new Notification.Builder(this,"mah_server").setContentTitle("محاسبي PRO").setContentText("الخادم يعمل على المنفذ 8787").setSmallIcon(android.R.drawable.stat_sys_upload_done).setOngoing(true).build();}
 static String sha(String s)throws Exception{MessageDigest m=MessageDigest.getInstance("SHA-256");return hex(m.digest(s.getBytes(StandardCharsets.UTF_8)));}
 static String hex(byte[] b){StringBuilder x=new StringBuilder();for(byte v:b)x.append(String.format("%02x",v));return x.toString();}
 class ServerThread extends Thread{ServerSocket ss; public void run(){try{ss=new ServerSocket(PORT,50,InetAddress.getByName("0.0.0.0"));while(running){Socket s=ss.accept();new Worker(s).start();}}catch(Exception e){}finally{try{if(ss!=null)ss.close();}catch(Exception e){}}}void close()throws Exception{running=false;if(ss!=null)ss.close();}}
 class Worker extends Thread{Socket s;Worker(Socket x){s=x;}public void run(){try{BufferedReader in=new BufferedReader(new InputStreamReader(s.getInputStream(),StandardCharsets.UTF_8));String line=in.readLine();if(line==null){s.close();return;}String[] p=line.split(" ");String method=p[0],path=p[1];int len=0;String h;while((h=in.readLine())!=null&&!h.isEmpty()){if(h.toLowerCase().startsWith("content-length:"))len=Integer.parseInt(h.substring(15).trim());}char[] c=new char[len];int n=0;while(n<len){int z=in.read(c,n,len-n);if(z<0)break;n+=z;}String body=new String(c);JSONObject out=route(method,path,body);byte[] bytes=out.toString().getBytes(StandardCharsets.UTF_8);String head="HTTP/1.1 200 OK\r\nContent-Type: application/json; charset=utf-8\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Headers: Authorization, Content-Type\r\nAccess-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS\r\nContent-Length: "+bytes.length+"\r\nConnection: close\r\n\r\n";OutputStream o=s.getOutputStream();o.write(head.getBytes(StandardCharsets.UTF_8));o.write(bytes);o.flush();s.close();}catch(Exception e){try{s.close();}catch(Exception x){}}}}
 JSONObject route(String m,String path,String body)throws Exception{if(m.equals("OPTIONS"))return new JSONObject().put("ok",true);if(path.equals("/health"))return new JSONObject().put("ok",true).put("service","mahasebi-phone-server-android");
  if(path.equals("/api/auth/login")&&m.equals("POST")){JSONObject b=new JSONObject(body);String u=b.optString("username").trim(),pw=b.optString("password");Cursor c=db.q("SELECT id,username,password_hash,role,active,permissions FROM users WHERE lower(username)=lower(?)",new String[]{u});if(!c.moveToFirst()||c.getInt(4)==0||!sha(pw).equals(c.getString(2)))return err("اسم المستخدم أو كلمة المرور غير صحيحة");JSONObject user=new JSONObject().put("id",c.getString(0)).put("username",c.getString(1)).put("role",c.getString(3)).put("active",c.getInt(4)).put("permissions",new JSONObject(c.getString(5)));return new JSONObject().put("token","android-local-token").put("user",user);}
  if(path.equals("/api/auth/users")&&m.equals("GET")){JSONArray a=new JSONArray();Cursor c=db.q("SELECT username FROM users WHERE role!='admin' AND active=1 ORDER BY username",null);while(c.moveToNext())a.put(new JSONObject().put("username",c.getString(0)));return new JSONObject().put("users",a);}
  if(path.equals("/api/state")&&m.equals("GET")){return db.state();}
  if(path.equals("/api/state")&&m.equals("PUT")){JSONObject b=new JSONObject(body);db.setState(b.optJSONObject("state"));return db.state();}
  if(path.equals("/api/sync/bootstrap")&&m.equals("POST")){JSONObject b=new JSONObject(body);db.setState(b.optJSONObject("state"));return db.state();}
  if(path.equals("/api/users")&&m.equals("GET")){return db.users();}
  if(path.equals("/api/users")&&m.equals("POST")){JSONObject b=new JSONObject(body);String id=b.optString("id",UUID.randomUUID().toString()),u=b.optString("username"),pw=b.optString("password");db.exec("INSERT INTO users(id,username,password_hash,role,active,permissions) VALUES(?,?,?,?,?,?)",new Object[]{id,u,sha(pw),"user",b.optInt("active",1),b.optJSONObject("permissions",new JSONObject()).toString()});return new JSONObject().put("ok",true);}
  return err("NOT_FOUND"); }
 JSONObject err(String x)throws Exception{return new JSONObject().put("error",x);}
 class DB extends SQLiteOpenHelper{DB(Context c){super(c,"server.db",null,1);}public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,username TEXT UNIQUE,password_hash TEXT,role TEXT,active INTEGER,permissions TEXT)");d.execSQL("CREATE TABLE IF NOT EXISTS app_state(id INTEGER PRIMARY KEY,json TEXT,revision INTEGER,updated_at TEXT)");Cursor c=d.rawQuery("SELECT COUNT(*) FROM users",null);c.moveToFirst();if(c.getInt(0)==0)try{d.execSQL("INSERT INTO users VALUES(?,?,?,?,?,?)",new Object[]{"admin","admin",sha("ChangeMeNow_123"),"admin",1,"{}"});}catch(Exception e){}c.close();}public void onUpgrade(SQLiteDatabase d,int a,int b){}Cursor q(String s,String[] a){return getReadableDatabase().rawQuery(s,a);}void exec(String s,Object[] a){getWritableDatabase().execSQL(s,a);}JSONObject state()throws Exception{Cursor c=q("SELECT json,revision,updated_at FROM app_state WHERE id=1",null);if(!c.moveToFirst()){c.close();return new JSONObject().put("state",JSONObject.NULL).put("revision",0);}JSONObject o=new JSONObject().put("state",new JSONObject(c.getString(0))).put("revision",c.getInt(1)).put("updatedAt",c.getString(2));c.close();return o;}void setState(JSONObject s){String now=new java.text.SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssXXX",Locale.US).format(new Date());exec("INSERT OR REPLACE INTO app_state(id,json,revision,updated_at) VALUES(1,?,?,?)",new Object[]{s==null?"{}":s.toString(),0,now});}JSONObject users()throws Exception{JSONArray a=new JSONArray();Cursor c=q("SELECT id,username,role,active,permissions FROM users ORDER BY role DESC,username",null);while(c.moveToNext())a.put(new JSONObject().put("id",c.getString(0)).put("username",c.getString(1)).put("role",c.getString(2)).put("active",c.getInt(3)).put("permissions",new JSONObject(c.getString(4))));c.close();return new JSONObject().put("users",a);}}
}
